### ISSUE TITLE
1: `arrange_()` is deprecated as of dplyr 0.7.0.

### ISSUE THREAD

**Issue by okendojo** [wasimaftab/LIMMA-pipeline-proteomics#3]
I am getting the below error when I run this pipeline on example data. Could you help in solving this?
Warning messages:
1: `arrange_()` is deprecated as of dplyr 0.7.0.
Please use `arrange()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `line.width` does not currently support multiple values. 
3: `line.width` does not currently support multiple values. 
4: `line.width` does not currently support multiple values. 
5: `line.width` does not currently support multiple values. 
6: The titlefont attribute is deprecated. Use title = list(font = ...) instead. 
7: `line.width` does not currently support multiple values. 
8: `line.width` does not currently support multiple values. 
9: The titlefont attribute is deprecated. Use title = list(font = ...) instead.

**Comment by wasimaftab** [comment]
these are warnings, not errors. I did not get the first warning related to dplyr, however, I got the `line.width` warnings. It's related to plotly and I would not worry too much as long I get the plots.  you must are run the code from RStudio by clicking **Source** button. See my environment and session details below. you might want to give it a try with the latest RStudio and 64 bit R.

    > sessionInfo()
    R version 3.6.3 (2020-02-29)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 20.04.1 LTS

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base

    other attached packages:
     [1] rstudioapi_0.11   htmlwidgets_1.5.1 qvalue_2.18.0     limma_3.42.2      plotly_4.9.2.1    ggplot2_3.3.2     matlab_1.0.2      MASS_7.3-51.6
     [9] stringr_1.4.0     dplyr_1.0.1
