### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by Xiaofei-git** [wasimaftab/LIMMA-pipeline-proteomics#4]
It is a really nice pipeline. How to cite? Is there a paper for it?

**Comment by wasimaftab** [comment]
Thank you for your interest and sorry for the super late reply. I have provided DOI in the [readme](https://github.com/wasimaftab/LIMMA-pipeline-proteomics) file which can be used to cite this repo. If you are using some sort of citation manager like endnote or BibTeX etc then you can refer to this [link](https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository) which explains how to cite GitHub repo.

**Comment by Xiaofei-git** [comment]
> Thank you for your interest and sorry for the super late reply. I have provided DOI in the [readme](https://github.com/wasimaftab/LIMMA-pipeline-proteomics) file which can be used to cite this repo. If you are using some sort of citation manager like endnote or BibTeX etc then you can refer to this [link](https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository) which explains how to cite GitHub repo.

Thanks!
